### ISSUE TITLE
errors trying to convert and use help

### ISSUE THREAD

**Issue by angelacode** [korczis/json2csv#2]
json2csv help convert  
    => NameError: undefined local variable or method `convert' for main:Object

    json2csv convert errors.json
    => NameError: undefined local variable or method `errors' for main:Object

**Comment by angelacode** [comment]
Here is the full stack trace:

<code>
NoMethodError: undefined method `convert' for main:Object
	from (irb):4
	from /usr/local/opt/rbenv/versions/2.1.5/bin/irb:11:in `<main>'
irb(main):005:0> puts caller
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/workspace.rb:86:in `eval'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/workspace.rb:86:in `evaluate'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/context.rb:380:in `evaluate'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:492:in `block (2 levels) in eval_input'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:624:in `signal_status'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:489:in `block in eval_input'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `loop'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `catch'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:397:in `block in start'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:396:in `catch'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/irb.rb:396:in `start'
/usr/local/opt/rbenv/versions/2.1.5/bin/irb:11:in `<main>'
=> nil
</code>

**Comment by korczis** [comment]
Can you provide sample data file, please?
